[package]
name = "treq-app"
version.workspace = true
edition.workspace = true

[dependencies]
treq-core = { path = "../treq-core" }
gpui = { workspace = true }
anyhow = { workspace = true }
dirs = { workspace = true }
serde = { workspace = true }
toml = "0.8"
serde_json = { workspace = true }
unicode-segmentation = "1"